### ISSUE TITLE
url option is vulnerable to XSS (Cross Site Scripting)

### ISSUE THREAD

**Issue by bunnypouts** [nandi95/vue-toastify#26]
The url option is vulnerable to XSS.
filter the url properly to prevent XSS for more on this please visit https://owasp.org/www-community/xss-filter-evasion-cheatsheet
There should be events to handle javascript execution.

![image](https://user-images.githubusercontent.com/42698103/119402169-30b5d180-bcfa-11eb-9089-a752fdbc072c.png)

**Comment by nandi95** [comment]
Thanks for the issue!
It seems this can be fixed by adding [encodeURI](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) [here](https://github.com/nandi95/vue-toastify/blob/master/src/components/linkable.js#L30) and [here](https://github.com/nandi95/vue-toastify/blob/master/src/components/linkable.js#L22)

PRs are welcome if not I will release a fix as soon as possible, in the meantime the same `encodeURI` can be done by the developer who uses the package.
